name: Build LaTeX presentation (2023)
on:   
  pull_request:
    branches: [ "main" ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: Conference 2023 Materials/presentation/
          root_file: presentation.tex
          latexmk_shell_escape: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Presentation
          path: Conference 2023 Materials/presentation/presentation.pdf
